### PR TITLE
Port package version discovery from pkg_resources [deprecated] to importlib+distutils

### PR DESCRIPTION
**Pull request by xaf-cv**
A quick fix for "ImportError: No module named pkg_resources".

Context: "Use of pkg_resources is deprecated in favor of [importlib.resources](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources), [importlib.metadata](https://docs.python.org/3.11/library/importlib.metadata.html#module-importlib.metadata) and their backports ([importlib_resources](https://pypi.org/project/importlib_resources), [importlib_metadata](https://pypi.org/project/importlib_metadata)). Some useful APIs are also provided by [packaging](https://pypi.org/project/packaging) (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions." - https://setuptools.pypa.io/en/latest/pkg_resources.html

Thank you for your work on the library!

### CODE REVIEW

**Comment by f-dangel** [comment]
Thanks for setting this up. Currently the tests are failing in Python 3.7. What is the minimum python version required to make this work? (I'm okay deprecating Python 3.7+3.8)/

**Comment by xaf-cv** [comment]
You are welcome. The importlib.metadata has been introduced in 3.8, so only 3.7 needs to be deprecated. I have updated the corresponding definitions. GH-Actions can now pass with no issues.

**Comment by adamjstewart** [comment]
```
ModuleNotFoundError: No module named 'distutils'
```
distutils was removed in Python 3.12, can we use packaging instead?

**Comment by f-dangel** [comment]
Hi Adam,

great proposal! I don't have much time to get to this at the moment. You could follow [this PR](https://github.com/f-dangel/backpack/pull/332/files) from a different project with very similar structure that applied this migration procedure. 

Happy to review a PR :)

Felix

**Comment by f-dangel** [comment]
@adamjstewart, thanks for #39! You should now be able to use version `0.2.3` or higher of this package with Python 3.12.

**Pull request merged**
